version: '2'
services:
    tradinglearning-elasticsearch:
        container_name: tradinglearning-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/tradinglearning/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
